insert into clientes (cidade, nome, uf) values ('João das Couves (1)', 'São Paulo', 'SP');
insert into clientes (cidade, nome, uf) values ('João das Neves (2)', 'São Paulo', 'SP');
insert into clientes (cidade, nome, uf) values ('José de Arimatéia (3)', 'São Paulo', 'SP');
insert into clientes (cidade, nome, uf) values ('Paulo das Couves (4)', 'São Paulo', 'SP');
insert into clientes (cidade, nome, uf) values ('Rodrigo Joaquim (5)', 'São Vicente', 'SP');
insert into clientes (cidade, nome, uf) values ('Henrique Silva (6)', 'Meridiano', 'SP');
insert into clientes (cidade, nome, uf) values ('Valdirene Couves (7)', 'Sorocaba', 'SP');
insert into clientes (cidade, nome, uf) values ('Mariana Couves (8)', 'Sorocaba', 'SP');
insert into clientes (cidade, nome, uf) values ('Maria Silva (9)', 'Belo Horizonte', 'MG');
insert into clientes (cidade, nome, uf) values ('Joaquina Alvares (10)', 'Ipatinga', 'MG');
insert into clientes (cidade, nome, uf) values ('Valkiria Couves(11)', 'Ipatinga', 'MG');
insert into clientes (cidade, nome, uf) values ('João das Marias (12)', 'Blumenau', 'SC');
insert into clientes (cidade, nome, uf) values ('Berta Bens (13)', 'Blumenau', 'SC');
insert into clientes (cidade, nome, uf) values ('Aldeide Pinto (14)', 'São Paulo', 'SP');
insert into clientes (cidade, nome, uf) values ('Joaquina Valeris (15)', 'São Paulo', 'SP');
insert into clientes (cidade, nome, uf) values ('Paulo Virtuoso (16)', 'São Paulo', 'SP');
insert into clientes (cidade, nome, uf) values ('Vigário da Silva (17)', 'São Paulo', 'SP');
insert into clientes (cidade, nome, uf) values ('João das Ovelhas (18)', 'Porto Alegre', 'RS');
insert into clientes (cidade, nome, uf) values ('Nardini (19)', 'Porto Alegre', 'RS');
insert into clientes (cidade, nome, uf) values ('Cristiane (20)', 'Porto Alegre', 'RS');
